### ISSUE TITLE
Log request duration

### ISSUE THREAD

**Issue by lorenyu** [navapbc/template-application-flask#111]
Idea from [this PR comment](https://github.com/navapbc/template-application-flask/pull/108#discussion_r1090947996) to log the request duration in milliseconds

implementation note:
- could potentially put start time on flask.g in before_request, then in after_request find difference between start and end time

**Comment by rsk2** [comment]
Hi @lorenyu, I looked at the code and I had a few questions regarding this issue:

- In which routine in `flask_logger.py` do you want to put the start time in flask.g?

- Would the request time be calculated in `_log_end_request` and be added to `extra` ?

**Comment by lorenyu** [comment]
@rsk2

> In which routine in flask_logger.py do you want to put the start time in flask.g?

we could add a new before_request handler in flask_logger, something like like `app.before_request(_track_request_start_time)`

> Would the request time be calculated in _log_end_request and be added to extra ?

yeah exactly

**Comment by lorenyu** [comment]
@rsk2 btw i don't recognize your github username. have we met before?

**Comment by rsk2** [comment]
No @lorenyu, we haven't. I am interested in contributing.

**Comment by lorenyu** [comment]
Oh I see! Well, nice to meet you!

**Comment by rsk2** [comment]
> Oh I see! Well, nice to meet you!

Nice meeting you too! Sorry I wasn't really sure how to offer to contribute. So I just asked the questions I had.

**Comment by lorenyu** [comment]
No need to apologize!

**Comment by rsk2** [comment]
Can I work on this ticket?

**Comment by lorenyu** [comment]
Sure! Go for it!

**Comment by rsk2** [comment]
@lorenyu 

> > In which routine in flask_logger.py do you want to put the start time in flask.g?
> 
> we could add a new before_request handler in flask_logger, something like like `app.before_request(_track_request_start_time)`

This would cause multiple `before _request` handlers to be registered, right? Since you currently already have `_log_start_request` added.

**Comment by lorenyu** [comment]
yeah, that's true. there are currently already multiple before_request handlers, so i think that's ok.

**Comment by rsk2** [comment]
@lorenyu , I have created a PR for this. Can you please review?
