### ISSUE TITLE
Look into alternatives to connexion for flask openAPI support

### ISSUE THREAD

**Issue by lorenyu** [navapbc/template-application-flask#12]
See [slack thread](https://nava.slack.com/archives/C03G1SWD9H7/p1663703304981579)

Quick google shows a bunch of options, but not sure which is best:
- [flask-rest-api](https://flask-rest-api.readthedocs.io/en/stable/openapi.html)
- [flassger](https://github.com/flasgger/flasgger)
- [flask-openapi3](https://luolingchun.github.io/flask-openapi3/)
- [apiflask](https://apiflask.com/openapi/)

**Comment by lorenyu** [comment]
@chouinar i'm taking a pass at refining the backlog and was trying to remember where we landed on this. do you remember?

**Comment by chouinar** [comment]
This eventually became an ADR I wrote + https://github.com/navapbc/template-application-flask/pull/20 - but we ran into some issues on getting things to be super happy, and it stalled.

**Comment by lorenyu** [comment]
Ah right I remember now. Maybe I'll take a look at that PR to refresh my memory and see if I can pick it back up.
