### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by lorenyu** [navapbc/template-application-flask#19]
# Context

template-application-flask still doesn't have CI. We want to add a `ci-app.yml` that runs the checks for the flask application. This CI should be able to be used on any project that uses the template.

See this [github thread](https://github.com/navapbc/template-infra/pull/106#discussion_r982855881)

**Comment by lorenyu** [comment]
@chouinar I saw you built the CI for WIC, was wondering if you could port it over to the template

**Comment by chouinar** [comment]
The PR-run linting/test run should be easily copied over, that shouldn't require any change other than the name.

The deploy bit might be trickier to make generic as it hard-codes a lot of the account IDs and requires an AWS account - which might not be available. How would we want to handle those?

**Comment by lorenyu** [comment]
@chouinar yeah this ticket is just for CI. Deploy can be out of scope for now.
