### ISSUE TITLE
Lint yml files (e.g. in .github/workflows)

### ISSUE THREAD

**Issue by lorenyu** [navapbc/template-application-flask#25]

**Comment by yoomlam** [comment]
For consideration:
- https://github.com/rhysd/actionlint
- https://github.com/adrienverge/yamllint
- https://github.com/stoplightio/spectral
- https://github.com/super-linter/super-linter

**Comment by lorenyu** [comment]
thanks!

**Comment by lorenyu** [comment]
Added in this PR https://github.com/navapbc/template-infra/pull/419
