### ISSUE TITLE
Update top-level README with instructions and details about usage

### ISSUE THREAD

**Issue by chouinar** [navapbc/template-application-flask#5]

**Comment by lorenyu** [comment]
@chouinar is this still needed?

**Comment by chouinar** [comment]
I think I did this somewhere in the work? I added whatever I intended to in the first pass, although know there's a lot more that would be good to add still.

**Comment by lorenyu** [comment]
Oh ok, I'll mark this as completed then. We can always create new tickets as we discover more areas that need work
